branch-defaults:
  default:
    environment: hello-eb-dev2
environment-defaults:
  hello-eb-dev2:
    branch: null
    repository: null
global:
  application_name: hello-eb
  default_ec2_keyname: lucatic_key
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
